# PyLogPlus
#
# config.py
# PL+ main configuration file
#
# Copyright © 2021 coresdev
#
# This product is free software, it is licenced under the GNU General Public Licence v3
# More information in LICENCE
#
# Made with <3 using python

# PL+ messaging config
PYLOGPLUS_INITIALIZING_MESSAGE_ENABLE = True  # Print 'PyLogPlus initializing' or configured message when PL+ is loaded
PYLOGPLUS_INITIALIZING_MESSAGE = 'PyLogPlus initializing'
PYLOGPLUS_READY_MESSAGE_ENABLE = True  # Print 'PyLogPlus is ready' or configured message when PL+ is done loading
PYLOGPLUS_READY_MESSAGE = 'PyLogPlus is ready'
PYLOGPLUS_DO_TEST = True  # Do a log test for each level upon library load

# PL+ extra feature configuration
PYLOGPLUS_ENABLE_TEST = True  # Allow testing
PYLOGPLUS_ENABLE_DEBUG_TEST = True  # Enable the .testDebug method for testing debug output and formatting
PYLOGPLUS_ENABLE_INFO_TEST = True  # Enable the .testInfo method for testing info output and formatting
PYLOGPLUS_ENABLE_WARNING_TEST = True  # Enable the .testWarning method for testing warning output and formatting
PYLOGPLUS_ENABLE_ERROR_TEST = True  # Enable the .testError method for testing error output and formatting
PYLOGPLUS_ENABLE_FATAL_TEST = True  # Enable the .testFatal method for testing fatal output and formatting

# PL+ Log configuration
PYLOGPLUS_DEFAULT_NAME = 'Program'  # Default name for loggers that do not set one
PYLOGPLUS_LEVEL_DEBUG_DISPLAY = 'DEBUG'  # Display name for the debug level
PYLOGPLUS_LEVEL_INFO_DISPLAY = 'INFO'  # Display name for the info level
PYLOGPLUS_LEVEL_WARNING_DISPLAY = 'WARNING'  # Display name for the warning level
PYLOGPLUS_LEVEL_ERROR_DISPLAY = 'ERROR'  # Display name for the error level
PYLOGPLUS_LEVEL_FATAL_DISPLAY = 'FATAL'  # Display name for the fatal level
PYLOGPLUS_NAME_VARIABLE = '%name%'  # Variable used for the message name
PYLOGPLUS_TIME_VARIABLE = '%time%'  # Variable used for the message time
PYLOGPLUS_TIME_FORMAT = '%hour%:%minute%:%second%'  # Format used for the message time
PYLOGPLUS_MESSAGE_VARIABLE = '%message%'  # Variable used for the message content
PYLOGPLUS_LOG_FORMAT = '[%time%] [%name%/%level%]: %message%'  # Format to be used in logs.

# PL+ Custom class configuration
PYLOGPLUS_LOAD_CUSTOM_CLASSES = True  # Should the library load custom classes?
PYLOGPLUS_ENABLE_CUSTOM_LOGGER = True  # Enable loading of custom logger classes
PYLOGPLUS_ENABLE_CUSTOM_REGISTRY = True  # Enable API support for custom registry classes

# DO NOT MODIFY THE LINES BELOW THIS MARKER
PYLOGPLUS_REGISTRY_API_ENABLE = True
PYLOGPLUS_REGISTRY_API_VERSION = '1.0.7'
PYLOGPLUS_REGISTRY_API_PUBLIC = True
PYLOGPLUS_CONFIG_IMPORT_VERSION = 27
PYLOGPLUS_CODEC_VERSION = 27


class PyLogPlusUserConfig:
    PYLOGPLUS_INITIALIZING_MESSAGE_ENABLE = None
    PYLOGPLUS_INITIALIZING_MESSAGE = None
    PYLOGPLUS_READY_MESSAGE_ENABLE = None
    PYLOGPLUS_READY_MESSAGE = None
    PYLOGPLUS_DO_TEST = None
    PYLOGPLUS_ENABLE_TEST = None
    PYLOGPLUS_ENABLE_DEBUG_TEST = None
    PYLOGPLUS_ENABLE_INFO_TEST = None
    PYLOGPLUS_ENABLE_WARNING_TEST = None
    PYLOGPLUS_ENABLE_ERROR_TEST = None
    PYLOGPLUS_ENABLE_FATAL_TEST = None
    PYLOGPLUS_DEFAULT_NAME = None
    PYLOGPLUS_LEVEL_DEBUG_DISPLAY = None
    PYLOGPLUS_LEVEL_INFO_DISPLAY = None
    PYLOGPLUS_LEVEL_WARNING_DISPLAY = None
    PYLOGPLUS_LEVEL_ERROR_DISPLAY = None
    PYLOGPLUS_LEVEL_FATAL_DISPLAY = None
    PYLOGPLUS_NAME_VARIABLE = None
    PYLOGPLUS_TIME_VARIABLE = None
    PYLOGPLUS_TIME_FORMAT = None
    PYLOGPLUS_MESSAGE_VARIABLE = None
    PYLOGPLUS_LOG_FORMAT = None
    PYLOGPLUS_LOAD_CUSTOM_CLASSES = None
    PYLOGPLUS_ENABLE_CUSTOM_LOGGER = None
    PYLOGPLUS_ENABLE_CUSTOM_REGISTRY = None
    PYLOGPLUS_REGISTRY_API_ENABLE = None
    PYLOGPLUS_REGISTRY_API_VERSION = None
    PYLOGPLUS_REGISTRY_API_PUBLIC = None
    PYLOGPLUS_CONFIG_IMPORT_VERSION = None
    PYLOGPLUS_CODEC_VERSION = None

    def __init__(self):
        self.PYLOGPLUS_INITIALIZING_MESSAGE_ENABLE = PYLOGPLUS_INITIALIZING_MESSAGE_ENABLE
        self.PYLOGPLUS_INITIALIZING_MESSAGE = PYLOGPLUS_INITIALIZING_MESSAGE
        self.PYLOGPLUS_READY_MESSAGE_ENABLE = PYLOGPLUS_READY_MESSAGE_ENABLE
        self.PYLOGPLUS_READY_MESSAGE = PYLOGPLUS_READY_MESSAGE
        self.PYLOGPLUS_DO_TEST = PYLOGPLUS_DO_TEST
        self.PYLOGPLUS_ENABLE_TEST = PYLOGPLUS_ENABLE_TEST
        self.PYLOGPLUS_ENABLE_DEBUG_TEST = PYLOGPLUS_ENABLE_DEBUG_TEST
        self.PYLOGPLUS_ENABLE_INFO_TEST = PYLOGPLUS_ENABLE_INFO_TEST
        self.PYLOGPLUS_ENABLE_WARNING_TEST = PYLOGPLUS_ENABLE_WARNING_TEST
        self.PYLOGPLUS_ENABLE_ERROR_TEST = PYLOGPLUS_ENABLE_ERROR_TEST
        self.PYLOGPLUS_ENABLE_FATAL_TEST = PYLOGPLUS_ENABLE_FATAL_TEST
        self.PYLOGPLUS_DEFAULT_NAME = PYLOGPLUS_DEFAULT_NAME
        self.PYLOGPLUS_LEVEL_DEBUG_DISPLAY = PYLOGPLUS_LEVEL_DEBUG_DISPLAY
        self.PYLOGPLUS_LEVEL_INFO_DISPLAY = PYLOGPLUS_LEVEL_INFO_DISPLAY
        self.PYLOGPLUS_LEVEL_WARNING_DISPLAY = PYLOGPLUS_LEVEL_WARNING_DISPLAY
        self.PYLOGPLUS_LEVEL_ERROR_DISPLAY = PYLOGPLUS_LEVEL_ERROR_DISPLAY
        self.PYLOGPLUS_LEVEL_FATAL_DISPLAY = PYLOGPLUS_LEVEL_FATAL_DISPLAY
        self.PYLOGPLUS_NAME_VARIABLE = PYLOGPLUS_NAME_VARIABLE
        self.PYLOGPLUS_TIME_VARIABLE = PYLOGPLUS_TIME_VARIABLE
        self.PYLOGPLUS_TIME_FORMAT = PYLOGPLUS_TIME_FORMAT
        self.PYLOGPLUS_MESSAGE_VARIABLE = PYLOGPLUS_MESSAGE_VARIABLE
        self.PYLOGPLUS_LOG_FORMAT = PYLOGPLUS_LOG_FORMAT
        self.PYLOGPLUS_LOAD_CUSTOM_CLASSES = PYLOGPLUS_LOAD_CUSTOM_CLASSES
        self.PYLOGPLUS_ENABLE_CUSTOM_LOGGER = PYLOGPLUS_ENABLE_CUSTOM_LOGGER
        self.PYLOGPLUS_ENABLE_CUSTOM_REGISTRY = PYLOGPLUS_ENABLE_CUSTOM_REGISTRY
        self.PYLOGPLUS_REGISTRY_API_ENABLE = PYLOGPLUS_REGISTRY_API_ENABLE
        self.PYLOGPLUS_REGISTRY_API_VERSION = PYLOGPLUS_REGISTRY_API_VERSION
        self.PYLOGPLUS_REGISTRY_API_PUBLIC = PYLOGPLUS_REGISTRY_API_PUBLIC
        self.PYLOGPLUS_CONFIG_IMPORT_VERSION = PYLOGPLUS_CONFIG_IMPORT_VERSION
        self.PYLOGPLUS_CODEC_VERSION = PYLOGPLUS_CODEC_VERSION
        return self
# DO NOT MODIFY THE LINES ABOVE THIS MARKER
